In [49]:
import numpy as np
import time as t

#Ejercicio 1

#print(np.array([[1,2,3,4],[4,5,6,7],[8,9,10,11]]))

a = np.arange(1,13,).reshape(3,4)
print(a)
print("-----------------------------------------------------")



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------------------------------------


In [50]:
#Ejercicio 2
colection = []

colection2 = np.random.randint(0,101,[5000,5000])
   
a1 = t.time()
sum = 0
for i in range (5000):
    for j in range(5000):
        sum = colection2[i][j]+sum
a2 = t.time()
sum2 = np.sum(colection2)
a3 = t.time()


print("con for", a2-a1 )
print("con sum", a3-a1)
print(colection2)

print (sum)

print (sum2)

print("-----------------------------------------------------")


con for 10.367363691329956
con sum 10.394366025924683
[[61 26 77 ... 99 63 69]
 [78 20 89 ... 16 56 12]
 [72 65 65 ... 64 55 53]
 ...
 [36 19 56 ... 58 57  0]
 [39 26 14 ... 66 31 26]
 [42 84 52 ... 90 50 47]]
1249791075
1249791075
-----------------------------------------------------


In [51]:
#Ejercicio 3


colection3 = np.random.randint(0,51,[10,5])
max = np.max(colection3)
min = np.min(colection3)

print (colection3)

print(max)

print(min)

[[50 26 25 22 38]
 [29 40 41 34 11]
 [19 31 18  1 49]
 [33 29 23  1 46]
 [ 3 28 22 16 17]
 [30 40 46 42 26]
 [43 29 32 45 44]
 [37 24 37 38 10]
 [ 1 43 29 14  5]
 [ 4 13  2 40 25]]
50
1
