imports

In [2]:
import numpy as np


inicializacion arr1

In [4]:
arr1 = np.empty((4,6))
arr1 = np.zeros((4,6))
arr1 = np.full((4,6), 10)

inicializacion arr2

In [6]:
arr2 = np.random.rand(4, 6)

inicializacion arr3

In [8]:
arr3 = np.random.randint(0, 15, 24)
arr3 = np.reshape(arr3, (3,8)) 


inicializacion lista

In [10]:
list_add = [5,5,5,5,5,5,0,0,0]

list1 = [1,2,3,4,5,6,7,8,9]
list2 = [1,2,3,4,5,6,7,8,9]
list3 = [1,2,3,4,5,6,7,8,9]
list4 = [1,2,3,4,5,6,7,8,9]
list5 = [1,2,3,4,5,6,7,8,9]
list6 = [1,2,3,4,5,6,7,8,9]

creacions array 4

In [12]:
arr4  = np.array([list1, list2, list3, list4, list5, list6])

In [13]:





#arr3 = np.random.randint(0, 15, 24)
#arr3 = arr3.reshape((4, 6)) # === arr3 = np.reshape(arr3, (4, 6)) 





# print("Size:", arr4.size)
# print("NDim:", arr4.ndim)
# print("Shape:", arr4.shape)

print(list_add * arr4)

[[ 5 10 15 20 25 30  0  0  0]
 [ 5 10 15 20 25 30  0  0  0]
 [ 5 10 15 20 25 30  0  0  0]
 [ 5 10 15 20 25 30  0  0  0]
 [ 5 10 15 20 25 30  0  0  0]
 [ 5 10 15 20 25 30  0  0  0]]
